modLoader="javafml"
loaderVersion="[47,)"
license="MIT"
[[mods]]
modId="spacetravel"
version="0.0.1"
displayName="Space Travel"
credits=""
authors="Povstalec"
displayTest="MATCH_VERSION"

description='''Space Travel'''
[[dependencies.astralvoyage]]
    modId="forge"
    mandatory=true
    versionRange="[47,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.astralvoyage]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1,1.21)"
    ordering="NONE"
    side="BOTH"